language: node_js
node_js: stable
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
- |
  npm start &
  SERVER_PID=$!
- xvfb-run polymer test --plugin local
- kill -9 $SERVER_PID
cache:
  directories:
    - node_modules
after_success:
  - node tasks/ci.js
