/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   web-socket.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

